# Archive job photos for the site (Muse's verified photo plan, 2026-10-09). Sources live in
# ../website-photos (patched copies in ../website-photos-processed win). gen.py turns each into img/p/<id>-<w>.webp.
# Captions and alt text never name a city: the archive jobs aren't geo-tagged, so we don't claim where they are.
# Never-ship list (tape measures, plates, house numbers, not-our-work) lives in FROM-MUSE-website-photo-plan §5.

PHOTOS = {  # id: (alt, caption)
 "001": ("Turf strips installed in the joints between concrete driveway pads", "After · turf strips in the joints"),
 "013": ("Crew laying a turf lawn beside a stamped concrete patio", "Install day · lawn going down"),
 "018": ("The same driveway before the turf: concrete pads with bare joints", "Before · bare joints"),
 "025": ("A freshly laid turf section with clean edges, running along a pool", "Fresh turf · tight edges"),
 "028": ("Curved turf lawn around a palm between a pool and a boat dock", "Pool to dock · curved lawn"),
 "031": ("Full-sun turf surface beside a pool deck", "Full sun · pool side"),
 "032": ("Narrow fenced side yard finished in turf", "Side yard · fenced run"),
 "033": ("AJ Turf crew seaming and laying turf in front of a home", "Crew at work · front yard"),
 "037": ("Turf lawn with a palm island next to a pool and a boat on the canal", "Canal home · pool and palm"),
 "039": ("Turf rolled out across a backyard with palms, the install coming together", "Coming together · day one"),
 "041": ("Crew unrolling a turf roll across a prepared backyard", "Crew at work · rollout"),
 "043": ("Wide turf lawn under coconut palms behind a waterfront home", "Palm lawn · waterfront"),
 "046": ("Turf lawn with a planted tree bed along a canal seawall", "Canal lawn · tree bed"),
 "049": ("Curved turf front yard around a planted bed with a statue", "Front yard · curved beds"),
 "053": ("Modern front yard with turf framing concrete driveway pads", "Front yard · driveway pads"),
 "060": ("Fenced backyard finished in turf with raised planter boxes", "Fenced yard · planters"),
 "068": ("Turf surrounding a curved pool and spa on a canal-front lot", "Pool and spa · canal lot"),
 "069": ("Turf side yard running between a white house and a hedge", "Side yard · hedge line"),
 "070": ("Backyard before the install: bare dirt around a new pool", "Before · bare dirt"),
 "074": ("The same backyard after: turf around the palms beside the pool", "After · turf to the pool"),
 "093": ("Turf lawn meeting a stone paver walkway under palms", "Turf to pavers · palms"),
 "095": ("Turf seam being glued along the concrete border, with seam tape laid out", "The method · seam and glue"),
 "098": ("Backyard turf lawn with a patio dining set", "Backyard · dining lawn"),
 "107": ("Long fenced turf run beside a pool", "Pool run · fenced"),
 "111": ("Turf lawn behind a pool with Adirondack chairs", "Pool lawn · chairs out"),
 "114": ("Small fenced turf yard with white planter boxes", "Small yard · planters"),
 "120": ("Turf backyard with a dining table under a shade tree", "Backyard · shade tree"),
 "124": ("Turf along a brick-edged pool with a garden behind it", "Pool edge · brick coping"),
 "130": ("Curved turf bed and turf stepping strips along a front walkway", "Front walk · turf strips"),
 "134": ("Fenced backyard of turf with planter boxes", "Fenced yard · full lawn"),
 "135": ("Turf putting strip running beside a pool and fence", "Pool side · putting strip"),
 "137": ("Bright turf side yard along a hedge", "Side yard · open run"),
 "142": ("Open turf lawn under tall coconut palms", "Open lawn · tall palms"),
 "144": ("Turf lawn curving between a pool and a canal with boats docked", "Pool to canal · curved lawn"),
 "147": ("Turf lawn with a planted island along a canal seawall", "Canal lawn · planted island"),
 "161": ("Curved turf bed around a palm with turf strips on the walkway", "Front yard · palm bed"),
 "176": ("Turf front yard curving along a brick paver path", "Front yard · paver path"),
 "187": ("Crew walking a finished backyard turf lawn", "Coming together · walkthrough"),
 "189": ("Turf set into natural flagstone pavers beside a garden", "Turf in flagstone"),
 "190": ("Turf lawn behind a pool lined with lounge chairs", "Pool lawn · lounge row"),
 "196": ("Turf side yard beside a white house and a sand path", "Side yard · sand path"),
 "201": ("Turf backyard with a patio table beside a white house", "Backyard · patio table"),
 "230": ("Turf lawn with a planted bed beside a canal and docks", "Canal lawn · planted bed"),
 "232": ("Close-up of turf blades and texture", "Up close · the turf"),
 "237": ("Turf lawn with a tree bed along a canal seawall, seen from above", "Canal lawn · from above"),
 "246": ("Turf lawn curving around a palm beside a stone walkway", "Palm lawn · curved edge"),
 "248": ("Crew rolling turf out over a prepared base", "Install · rollout"),
 "249": ("Close-up of turf blades in full sun", "Up close · full sun"),
 "252": ("Backyard before the install: bare dirt beside a pool", "Before · bare dirt"),
 "256": ("Turf run between a spa and a white railing", "Spa side · turf run"),
 "257": ("Freshly installed turf lawn with the crew finishing up", "Install · finishing up"),
 "269": ("Turf island around a young tree in a concrete driveway", "Driveway island"),
 "281": ("The same backyard after: turf beside the pool deck and tiki huts", "After · turf by the tiki huts"),
 "290": ("Turf lawn finished around planted beds in a backyard", "Coming together · finished beds"),
 "293": ("Long turf run beside a fence and pool deck", "Fence line · pool deck"),
 "298": ("Installer finishing a seam along the fence line", "Install · seam finish"),
 "299": ("Turf lawn beside a tiki hut and a coral rock garden", "Tiki yard · coral rock"),
 "green_backyard_01": ("Fenced backyard putting green with three flags", "Putting green · fenced yard"),
 "green_bigyard_01": ("Putting green with fringe and four flags in a fenced yard", "Putting green · four cups"),
 "green_canal_01": ("Putting green with fringe on a lakefront patio", "Putting green · on the water"),
 "green_canal_02": ("Putting green with fringe beside a tiki hut on the water", "Putting green · tiki side"),
 "green_canal_03": ("Putting green along a home's patio with a tiki hut behind it", "Putting green · patio edge"),
 "green_waterfront_01": ("Long putting green with several flags behind a waterfront home", "Putting green · long run"),
 "green_waterfront_02": ("Putting green with flags along a hedge behind a raised home", "Putting green · hedge line"),
 "green_waterfront_03": ("Putting green with fringe framed by white rock borders", "Putting green · rock border"),
 "green_waterfront_04": ("Putting green with fringe and a flag in front of a raised home", "Putting green · front flag"),
}

# Before/after pairs are listed as ("pair", before, after) so they always render side by side.
HOME = ["028", "144", "246", "230", "201", "049", "111", "074", "189", "114", "green_backyard_01", "043"]
SERVICE = {
 "artificial-turf-installation": ["142", "176", "098", "120", "269", "134"],
 "pet-turf": ["060", "134", "032", "137", "232"],
 "putting-greens": ["green_canal_01", "green_canal_02", "green_waterfront_01", "green_waterfront_02", "green_waterfront_04", "green_bigyard_01"],
 "pool-and-paver-turf": ["068", "124", "190", "256", "093", "281"],
 "turf-repair": [("pair", "018", "001"), "025", "013"],
}
CITY = {
 "Fort Myers": ["037", "135", "046", "green_waterfront_03"],
 "Cape Coral": ["green_canal_03", "293", "130", "299"],
 "Naples": ["053", "147", "161"],
 "Estero": ["107", "249", "196", "031"],
 "Bonita Springs": ["237", "190", "232", "069"],
 "Sanibel": ["043", "068", "111", "124"],
 "Lehigh Acres": ["114", "120", "269", "098"],
}
# Muse's 22-photo wall, grouped into rails; each rail ends at the booking CTA
OUR_WORK_RAILS = [
 ("Pools &amp; <b>waterfront.</b>", ["028", "144", "068", "230", "111", "256", "037"]),
 ("Yards &amp; <b>lawns.</b>", ["246", "049", "201", "176", "299", "189", "093", "060", "032"]),
 ("Putting <b>greens.</b>", ["green_backyard_01", "green_canal_02"]),
 ("Before, after &amp; <b>on the job.</b>", [("pair", "070", "074"), ("pair", "252", "281"), "248", "257"]),
]
GUIDE = {
 "how-artificial-turf-is-installed": ["248", "025", "095", "298", "039", "290", "187"],
 "questions-to-ask-before-hiring-a-turf-installer": ["033", "041"],
 "how-hot-does-artificial-turf-get-in-florida": ["031", "249"],
}
